name: CI Frontend Build & Push Docker Images to GHCR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SERVER: ${{ secrets.EC2_HOST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Frontend
        run: |
          docker build -t ghcr.io/iteleshov/frontend:latest ./frontend
          docker push ghcr.io/iteleshov/frontend:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SERVER_SSH }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa
          ssh-agent bash -c 'echo "SSH agent started" && ssh-add ~/.ssh/id_rsa'
          ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts

      - name: Pull image
        run: |
          echo "Pulling the frontend image..."
          ssh ubuntu@$SERVER "docker compose pull frontend"   

      - name: Deploy image
        run: |
          echo "Deploying the frontend image..."
          ssh ubuntu@$SERVER "docker compose up -d frontend --force-recreate"    

